name: ci-qna

on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    services:
      mongodb_test:
        image: postgres:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{secrets.DB_TEST_USERNAME}}
          MONGO_INITDB_ROOT_PASSWORD: ${{secrets.DB_TEST_PASSWORD}}
          MONGO_INITDB_DATABASE: audit
        ports:
          - 27011:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Create .env
        run: touch .env

      - name: Test
        env:
          DB_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_TEST_USERNAME }}
        run: go test -v ./...
